### ISSUE TITLE
Joinfaces version

### ISSUE THREAD

**Issue by olaven** [arcuri82/testing_security_development_enterprise_systems#6]
When I am using joinfaces 3.2.3, I am not able to start 
spring boot application due to conflicting versions - joinfaces appears to use an older version of spring-security.
The project uses springboot 2.1.0.RELEASE. 

Upgrading to joinfaces 4.0.3 solved the issue :-) 

If this is not just a problem for me, it may be an idea to update version used in the course :-)

**Comment by arcuri82** [comment]
Hi,
 thanks for reporting this potential issue. but, if you look at quiz-game-part-11, that works fine. So it might be an issue with versioning of some specific libraries in the <dependencyManagment> (eg, cdi-api).
I can have a look at it next class
